// Generated by LiveScript 1.3.1
var ldcv, ldf;
ldcv = new ldCover({
  root: '.ldcv'
});
ldf = new ldFile({
  root: 'input',
  type: 'text',
  ldcv: ldcv
});
ldf.on('load', function(it){
  return textarea.value = it.map(function(it){
    return it.result;
  }).join('\n');
});