#!/usr/bin/env bash
REV=`git describe --always`
rm -rf demo/_public
git clone $(git remote get-url origin) --depth 1 -b gh-pages demo/_public
cd demo/_public
git rm -r *
cp -R ../static/ ./
git add *
git commit -m "regen for $REV"
git push
cd ../..
